[package]
name = "iced_video_player"
version = "0.1.0"
authors = ["jazzfool"]
edition = "2018"
resolver = "2"

[dependencies]
iced = { version="0.3", features=["image", "tokio"] }
iced_native = "0.4"
gstreamer = "0.17"
gstreamer-app = "0.17" # appsink 
glib = "0.14" # gobject traits and error type
tokio = { version="1", features=["time"] }
thiserror = "1"
url = "2" # media uri
num-rational = "0.4" # framerates come in rationals
num-traits = "0.2" # convert rationals to floats (ToPrimitive)

[package.metadata.nix]
systems = ["x86_64-linux"]
app = true
build = true
runtimeLibs = [
    "vulkan-loader",
    "wayland",
    "wayland-protocols",
    "libxkbcommon",
    "xorg.libX11",
    "xorg.libXrandr",
    "xorg.libXi",
]
buildInputs = [
    "libxkbcommon",
    "gst_all_1.gstreamer",
    "gst_all_1.gst-plugins-bad",
    "gst_all_1.gst-plugins-ugly",
    "gst_all_1.gst-plugins-good",
    "gst_all_1.gst-plugins-base",
]
